// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOez7b9_W5ApoE47P1XJ8ojDHqcHQRzc',
    appId: '1:610223730092:web:4ad245e25d883081cc5e09',
    messagingSenderId: '610223730092',
    projectId: 'fruits-hub-5be2c',
    authDomain: 'fruits-hub-5be2c.firebaseapp.com',
    storageBucket: 'fruits-hub-5be2c.appspot.com',
    measurementId: 'G-9VDT8D0G1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-ww9B26o5yQJKtScRrh3XHS4tUD2Rbs',
    appId: '1:610223730092:android:90ea271250261a07cc5e09',
    messagingSenderId: '610223730092',
    projectId: 'fruits-hub-5be2c',
    storageBucket: 'fruits-hub-5be2c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOez7b9_W5ApoE47P1XJ8ojDHqcHQRzc',
    appId: '1:610223730092:web:c3b3a1994ab324c3cc5e09',
    messagingSenderId: '610223730092',
    projectId: 'fruits-hub-5be2c',
    authDomain: 'fruits-hub-5be2c.firebaseapp.com',
    storageBucket: 'fruits-hub-5be2c.appspot.com',
    measurementId: 'G-ZHQWK29WHG',
  );

}