// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFZlMs1qwaCg9_oPxPpHazjfTtRBSoE8',
    appId: '1:435147053836:web:a83c113893ab696a4e0729',
    messagingSenderId: '435147053836',
    projectId: 'fruits-f7bfa',
    authDomain: 'fruits-f7bfa.firebaseapp.com',
    storageBucket: 'fruits-f7bfa.appspot.com',
    measurementId: 'G-NCEN1TN1JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDih5Ag9jdnZpG1gdGb103b_QdVn67iJtQ',
    appId: '1:435147053836:android:256e5682ec48d7e74e0729',
    messagingSenderId: '435147053836',
    projectId: 'fruits-f7bfa',
    storageBucket: 'fruits-f7bfa.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuFZlMs1qwaCg9_oPxPpHazjfTtRBSoE8',
    appId: '1:435147053836:web:7d6a08a19db29e6d4e0729',
    messagingSenderId: '435147053836',
    projectId: 'fruits-f7bfa',
    authDomain: 'fruits-f7bfa.firebaseapp.com',
    storageBucket: 'fruits-f7bfa.appspot.com',
    measurementId: 'G-0VQNKC1NLH',
  );
}
